@startuml
hide footbox
skinparam Shadowing false
skinparam BackgroundColor #f2f2f2
skinparam SequenceGroupBodyBackgroundColor transparent
skinparam roundcorner 10
skinparam ParticipantPadding 30
skinparam BoxPadding 10
skinparam SequenceGroupBorderColor #a0a0ff
skinparam SequenceMessageAlign center

participant CBE as cbe
participant CBC as cbc
collections MME as mme
participant FM as fm

cbe -> cbc: [1] CAP Alert
group once per MME involved in this test
    cbc -> mme: [2] WRITE-REPLACE WARNING REQUEST
    mme -> cbc: [3] WRITE-REPLACE WARNING RESPONSE
end
cbc --> cbe: [4] feedback
rnote over cbc
    Log unknown 
    TAI event
endrnote
cbc --> fm: [5] Alarm

group at least once per MME that controls eNBs in valid TAIs
    mme -> cbc: [6] WRITE-REPLACE WARNING INDICATION
end

cbc --> cbe: [7] feedback


@enduml