@startuml
hide footbox
skinparam Shadowing false
skinparam BackgroundColor #f2f2f2
skinparam SequenceGroupBodyBackgroundColor transparent
skinparam roundcorner 10
skinparam ParticipantPadding 30
skinparam BoxPadding 10
skinparam SequenceGroupBorderColor #a0a0ff
skinparam SequenceMessageAlign center

participant CBE as cbe
participant CBC as cbc
participant MME as mme

group Start alert
    cbe -> cbc: [1] CAP Alert
    cbc -> mme: [2] WRITE-REPLACE WARNING REQUEST
    mme -> cbc: [3] WRITE-REPLACE WARNING RESPONSE
end
note across: Broadcast runs for 1 broadcast period or more.
group Update alert
    cbe -> cbc: [4] CAP Alert
    group Option 1
        cbc -> mme: [5.a] WRITE-REPLACE WARNING REQUEST
        mme -> cbc: [6.a] WRITE-REPLACE WARNING RESPONSE
        rnote over cbc, mme
            Broadcasting updated message.
        endrnote
    end
    group Option 2
        cbc -> mme: [5.b] STOP WARNING REQUEST
        mme -> cbc: [6.b] STOP WARNING RESPONSE
        rnote over cbc, mme
            Original broadcast cancelled.
        endrnote
        cbc -> mme: [7.b] WRITE-REPLACE WARNING REQUEST
        mme -> cbc: [8.b] WRITE-REPLACE WARNING RESPONSE
        rnote over cbc, mme
            New broadcast activated.
        endrnote
    end
end
cbc --> cbe: feedback
@enduml