@startuml
hide footbox
skinparam Shadowing false
skinparam BackgroundColor #f2f2f2
skinparam SequenceGroupBodyBackgroundColor transparent
skinparam roundcorner 10
skinparam ParticipantPadding 30
skinparam BoxPadding 10
skinparam SequenceGroupBorderColor #a0a0ff
skinparam SequenceMessageAlign center

participant CBE as cbe
participant CBC as cbc
collections MME as mme

group Start alert
    cbe -> cbc: [1] CAP Alert
    cbc -> mme: [2] WRITE-REPLACE WARNING REQUEST
    mme -> cbc: [3] WRITE-REPLACE WARNING RESPONSE
    group One or more per MME
        rnote over mme
            Receiving responses 
            from eNBs
        endrnote
        mme -> cbc: [4] WRITE-REPLACE WARNING INDICATION
    end
end
note across: Broadcast runs for 1 broadcast period or more.

group Update alert area
    cbe -> cbc: [5] CAP Alert
    group Option 1
        group Stop broadcast completely
            cbc -> mme: [6.a] STOP WARNING REQUEST
            mme -> cbc: [7.a] STOP WARNING RESPONSE
            group One or more per MME
                rnote over mme
                    Receiving responses 
                    from eNBs
                endrnote
                mme -> cbc: [8.a] STOP WARNING INDICATION
            end
            rnote over cbc, mme
                Broadcast stopped completely.
            endrnote
        end
        group Re-start broadcast with new timing
            cbc -> mme: [9.a] WRITE-REPLACE WARNING REQUEST
            mme -> cbc: [10.a] WRITE-REPLACE WARNING RESPONSE
            group One or more per MME
                rnote over mme
                    Receiving responses 
                    from eNBs
                endrnote
                mme -> cbc: [11.a] WRITE-REPLACE WARNING INDICATION
            end
            rnote over cbc, mme
                Broadcast re-started with new periodicity and number of repetitions.
            endrnote
        end
    end
    group Option 2
        cbc -> mme: [6.b] WRITE-REPLACE WARNING REQUEST
        mme -> cbc: [7.b] WRITE-REPLACE WARNING RESPONSE
        group One or more per MME
                rnote over mme
                    Receiving responses 
                    from eNBs
                endrnote
                mme -> cbc: [8.b] WRITE-REPLACE WARNING INDICATION
            end
        rnote over cbc, mme
            Broadcasting alert with new periodicity and number of repetitions.
        endrnote
    end
end
cbc --> cbe: feedback
@enduml