@startuml
hide footbox
skinparam Shadowing false
skinparam BackgroundColor transparent
skinparam SequenceGroupBodyBackgroundColor transparent
skinparam roundcorner 10
skinparam ParticipantPadding 30
skinparam BoxPadding 10
skinparam SequenceGroupBorderColor #a0a0ff

participant CBE as cbe
box "CBC" #e0e0ff
participant FrontEnd as fe
collections GSM_Handler as handler
end box
collections BSC as bsc

cbe -> fe: [1] Alert
fe -> cbe: [2] Ack
loop one per BSC
    fe -> handler: [3.a] pws-GERAN 
    handler -> bsc: [4.a] WRITE-REPLACE
    alt success in all the cells
        bsc -> handler: [4.b] WRITE-REPLACE COMPLETE
    else failure in one or more cells
    bsc -> handler: [4.c] WRITE-REPLACE FAILURE 
    end
    handler -> fe: [3.b] ReportPWS-GERAN
end
fe -> cbe: [5] Report
@enduml