@startuml
hide footbox
skinparam Shadowing false
skinparam BackgroundColor transparent
skinparam SequenceGroupBodyBackgroundColor transparent
skinparam roundcorner 10
skinparam ParticipantPadding 30
skinparam BoxPadding 10
skinparam SequenceGroupBorderColor #a0a0ff

participant CBE as cbe
box "CBC" #e0e0ff
participant FrontEnd as fe
collections LTE_Handler as handlers
end box
collections MME as mme

cbe -> fe: [1] Cancel
fe -> cbe: [2] Ack
loop one per MME
    fe -> handlers: [3.a] pws-4G
    handlers -> mme: [4.a] WRITE-REPLACE WARNING REQUEST
    mme -> handlers: [4.b] WRITE-REPLACE WARNING RESPONSE
    handlers -> fe: [3.b] ReportPWS-4G
    opt if [4.a] includes "Send Write-Replace-Warning-Indication"
        mme -> handlers: [4.c] WRITE REPLACE WARNING INDICATION
        handlers -> fe: [3.c] AsyncReport
    end
    opt if one or more eNodeBs report failure in some cells
        loop for each eNodeB in which there is at least one failed cell
            mme -> handlers: [4.d] PWS FAILURE INDICATION
            handlers -> fe: [3.d] failureIndication-4G
        end
    end 
end
fe -> cbe: [5] Report
@enduml