@startuml
hide empty description
skinparam BackgroundColor transparent
state "Created" as crea
state "Pending Activation" as pend
state "Active" as act
state "Paused" as pau
state "Updating" as upd
state "Stopping" as stop
state "Stopped" as dest

[*] --> crea : Alert from CBE
crea -right-> pend : pws
pend --> act : asyncReport
act --> pau : failureIndication
pau --> pend : pws
act --> upd : UpdatePWS
upd --> act : reportUpdatePWS
act --> stop : stopPWS
act --> dest : campaign expired
stop --> dest : asyncReport
dest --> [*]
@enduml